### ISSUE TITLE
esta dando erro de usuario

### ISSUE THREAD

**Issue by lhmathias** [paulocsilvajr/prjSistemaCasaTintas#1]
esta dando erro de usuário

**Comment by paulocsilvajr** [comment]
Erro ao logar? Tenho que rever esse projeto, não mexo nele desde a época que fiz upload aqui no GitHub.
Favor relatar detalhadamente o processo que está dando problema, que vou reimplementar no meu PC atual e testar para corrigir.

**Comment by lhmathias** [comment]
Oi Paulo este erro foi erro meu eu simplesmente eu executei mysql sem ver as chaves extrangeiras!!!
então eu vi com mais detalhe o mysql que vc que vc deixou com o projeto esta funcionando corretamente muito obg pela atenção!!!

**Comment by lhmathias** [comment]
mas agora esta dando erro em abrir a Caixa!

**Comment by paulocsilvajr** [comment]
Vou reimplementar o projeto no meu PC e verificar esses problemas, realmente não me lembro como as tarefas são executadas. No fim se semana testo ele e tento dar um feedback.

**Comment by paulocsilvajr** [comment]
@lhmathias corrigi o erro ao abrir o caixa, foi uma validação não testada na época, pois o sistema sempre tinha um caixa aberto. Você pode conferir no último commit a versão atualizada [https://github.com/paulocsilvajr/prjSistemaCasaTintas/commit/0ad53a04a8132a9fb586def4567203a0c2277613](url). Qualquer outro problema, favor me comunicar, tentarei corrigir o mais breve possível.

**Comment by lhmathias** [comment]
obg pela ajuda!!!
